# Generated by Django 3.2.5 on 2021-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(height_field='350', upload_to='affliate_img', width_field='600')),
                ('desc', models.TextField()),
                ('url_img', models.URLField()),
            ],
        ),
    ]
