# Generated by Django 3.2.5 on 2021-07-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatemodel',
            name='img_height',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='affiliatemodel',
            name='img_width',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='affiliatemodel',
            name='img',
            field=models.ImageField(height_field='img_height', upload_to='affliate_img', width_field='img_width'),
        ),
    ]
